[build]
  # Skip running a build in Netlify — we ship a ready-to-serve static `build/` folder in the repo
  command = ""
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

# Production-only environment variables. It's safer to set secrets in the Netlify UI
# (Site → Site settings → Build & deploy → Environment) rather than in this file.
[context.production.environment]
  VITE_SUPABASE_PROJECT_ID = "kkpufplzmvaszigezfyf"
  VITE_SUPABASE_ANON_KEY = "REPLACE_WITH_ANON_KEY"
