/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kkpufplzmvaszigezfyf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcHVmcGx6bXZhc3ppZ2V6ZnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4Nzk3ODIsImV4cCI6MjA3NTQ1NTc4Mn0.BxcbMJh-VYHC1L0Ro7J_d9TRQ-fyOwmydkBITa6hB2k"